[project]
name = "best-shot"
version = "0.1.0"
description = "Take your best shot"
authors = [
    { name = "cyrus", email = "cyrus@zenbase.ai" },
    { name = "behradkhorram", email = "behrad@zenbase.ai" }
]
dependencies = [
    "ujson>=5.10.0",
]
readme = "README.md"
requires-python = ">= 3.8"

[project.optional-dependencies]
transformers = ["transformers>=4.46.2", "sentence-transformers>=3.2.1"]
openai = ["openai>=1.54.3"]
memory = ["numpy<2"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.3.3",
    "pytest-anyio>=0.0.0",
    "ipdb>=0.13.13",
    "ipython>=8.29.0",
    "beartype>=0.19.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/best_shot"]
